/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {

  home: [
    "intro",
    "resources"
  ],

  // By default, Docusaurus generates a sidebar from the docs folder structure
  mySidebar: [
    { type: 'autogenerated', dirName: 'explore' }
  ],

  appSidebar: [
    { type: 'autogenerated', dirName: 'app' }
  ],

};

module.exports = sidebars;
